### ISSUE TITLE
Connecting to non-localhost/authenticated database

### ISSUE THREAD

**Issue by brandonmoser** [thebergamo/start-hapiness#9]
I'm using your template to learn and understand Hapi, but I'm using a hosted sandbox Mongo DB, but can't seem to find how to add credentials. I've set the standard DB_USER and DB_PASS and added those to the getDatabaseURI() method, as shown here. The url module does not add `user:pass`, as expected. I'm going to post this similar question to `k7-mongoose`, as it is related.

```
function getDatabaseURI() {
  return url.format({
    protocol: 'mongodb',
    slashes: true,
    username: process.env.DB_USER || null,
    password: process.env.DB_PASS || null,
    hostname: process.env.DB_HOST || 'localhost',
    port: process.env.DB_PORT || 27017,
    pathname: process.env.DB_NAME || 'project',
});
```

**Comment by thebergamo** [comment]
Hey @brandonmoser in your case the generated URL match as a regular connectionString? If you want, you can just pass the connectionString itself to k7-mongoose. 

here is where the connectionString is merged with the default options: https://github.com/thebergamo/k7-mongoose/blob/master/lib/index.js#L91

Can you test, just passing the connectionString direct in the k7-mongoose option? And testing if the return of the function getDatabaseURI is correct?

**Comment by brandonmoser** [comment]
I ended up building the connection like this.
```
// load database
mongoose.connect(getDatabaseURI(), {
  user: process.env.DB_USER || null,
  pass: process.env.DB_PASS || null,
  useMongoClient: true,
  config: {
    autoIndex: (process.env.NODE_ENV != 'production'),
  },
});
function getDatabaseURI() {
  return url.format({
    protocol: 'mongodb',
    slashes: true,
    hostname: process.env.DB_HOST || 'localhost',
    port: process.env.DB_PORT || 27017,
    pathname: process.env.DB_NAME || 'project',
  });
}
```
